language: go
sudo: false
go:
  - 1.11.x
  - 1.12.x

env:
  - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

script:
  - go vet ./...
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...
  - go build

after_success:
  - bash <(curl -s https://codecov.io/bash)